[project]
name = "engg64"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.7",
    "notebook>=7.4.7",
    "opencv-python>=4.12.0.88",
    "ruff>=0.14.0",
    "seaborn>=0.13.2",
]
